version: '3.8'

services:
  # Redis for Celery background tasks
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Main FastAPI application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Celery worker for background tasks
  celery-worker:
    build: .
    command: celery -A services.background_processor worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

  # Celery beat for scheduled tasks (optional)
  celery-beat:
    build: .
    command: celery -A services.background_processor beat --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  redis_data: 